import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

/**
 * Complete Bible Chapter Titles/Subtitles (English)
 * Source: Austin Bible Church - https://austinbiblechurch.com/sites/default/files/documents/Bible_Chapter_Titles.pdf
 * Format: { bookOrder: [ chapter titles array ] }
 *
 * We use:
 *   - sectionTitle      = Vietnamese when available (BIBLE_CHAPTER_TITLES_VI), else English (for VI read view)
 *   - sectionTitleKJV  = English (KJV)
 *   - sectionTitleNIV  = English (NIV)
 */
const BIBLE_CHAPTER_TITLES_EN: Record<number, string[]> = {
  // Genesis (50 chapters)
  1: [
    "Creation & Recreation",
    "Creation & Recreation Recap",
    "The Fall of Man",
    "Cain Murders Abel",
    "Genealogies",
    "The Flood",
    "The Flood",
    "The Flood",
    "The Rainbow & Capital Punishment",
    "Genealogies",
    "The Tower of Babel",
    "The Call of Abraham",
    "The Cowboy Conflict",
    "The Kidnapping of Lot",
    "Abraham Believed God",
    "Ishmael is Born",
    "Abram becomes Abraham",
    "Abraham prays for Sodom",
    "Sodom is destroyed",
    "Abraham lies about Serah at Gerar",
    "The Birth of Isaac",
    "The Offering of Isaac",
    "The Death of Sarah",
    "The Bride for Isaac",
    "The Death of Abraham",
    "Abrahamic Covenant Confirmed to Isaac",
    "Jacob-Esau Birthright Conflict",
    "Abrahamic Covenant Confirmed to Jacob",
    "Jacob Marries Leah & Rachel",
    "Jacob's Cattle (method of breeding)",
    "Jacob Leaves Laban",
    "Jacob Becomes Israel",
    "Jacob's Reunion with Esau",
    "The Distress of Dinah",
    "Rachel Dies, Isaac Dies",
    "The Generations of Esau",
    "Joseph's Dream, Sold to Egypt",
    "The Shame of Judah",
    "Joseph, Potiphar, & Prison",
    "Joseph's Butler-Baker Dream",
    "Joseph, Minister of Agriculture",
    "Joseph's 10 Brothers to Egypt to buy corn",
    "Joseph's 11 Brothers to Egypt to buy corn",
    "Benjamin's Silver Cup",
    "Joseph Reveals All",
    "Jacob and family move to Egypt",
    "Joseph sells corn for land for Pharaoh",
    "Joseph's Sons, Double Portion",
    "Jacob's Evaluation of His Sons",
    "Bones of Joseph (Jacob & Joseph Die)",
  ],
  // Exodus (40 chapters)
  2: [
    "Slavery in Egypt",
    "The Birth of Moses",
    "The Burning Bush",
    "The Objections of Moses",
    "Increased Slavery",
    "Affirmation of Abrahamic Covenant",
    "The Ten Plagues (Part 1)",
    "The Ten Plagues (Part 2)",
    "The Ten Plagues (Part 3)",
    "The Ten Plagues (Part 4)",
    "The Ten Plagues (Part 5)",
    "The Ten Plagues (Part 6)",
    "Guidance by Pillar of Cloud & Fire",
    "Crossing of the Red Sea",
    "Wrong Kind of Water (Marah)",
    "Provision of Manna",
    "No Water Situation (Rephidim)",
    "Organization Man Jethro",
    "Arrival at Mt. Sinai",
    "The Ten Commandments",
    "Laws and Ordinances (Part 1)",
    "Laws and Ordinances (Part 2)",
    "Laws and Ordinances (Part 3)",
    "Laws and Ordinances (Part 4)",
    "Laws and Ordinances (Part 5)",
    "Laws and Ordinances (Part 6)",
    "Laws and Ordinances (Part 7)",
    "Laws and Ordinances (Part 8)",
    "Laws and Ordinances (Part 9)",
    "The Sabbath",
    "The Mosaic Covenant Ratified",
    "Golden Calf (Stone tablets broken)",
    "On to Canaan (Moses sees God)",
    "Second Tablets of Stone",
    "Tabernacle Parts Constructed (Part 1)",
    "Tabernacle Parts Constructed (Part 2)",
    "Tabernacle Parts Constructed (Part 3)",
    "Tabernacle Parts Constructed (Part 4)",
    "Tabernacle Parts Constructed (Part 5)",
    "The Tabernacle is Set Up",
  ],
  // Leviticus (27 chapters)
  3: [
    "The Sweet Savor Offerings - Burnt Offering",
    "The Sweet Savor Offerings - Meal Offering",
    "The Sweet Savor Offerings - Peace Offering",
    "The Non-Sweet Savor Offerings - Sin Offering",
    "The Non-Sweet Savor Offerings - Trespass Offering",
    "How to Apply the Five Offerings (Part 1)",
    "How to Apply the Five Offerings (Part 2)",
    "Consecration of the Priests",
    "Beginning of the Priest's Ministry",
    "Strange Fire—Nadab & Abihu",
    "The Food of Israel",
    "The Law of Motherhood",
    "Leprosy!",
    "Cleansing of the Leper",
    "A Holy God, A Holy People",
    "The Day of Atonement",
    "Significance of Blood",
    "How a Nation Falls (Part 1)",
    "How a Nation Falls (Part 2)",
    "How a Nation Falls (Part 3)",
    "The Walk and Work of the Priests (Part 1)",
    "The Walk and Work of the Priests (Part 2)",
    "The Feasts of the Lord",
    "Cursing and Capital Punishment",
    "The Law of the Land (The Blessing and the Curse)",
    "The Five Cycles of Discipline",
    "Vows, First-Fruits, Dedications, the Tithe",
  ],
  // Numbers (36 chapters)
  4: [
    "The Numbering of the Tribes",
    "The Arrangement of the Camp (Part 1)",
    "The Arrangement of the Camp (Part 2)",
    "The Arrangement of the Camp (Part 3)",
    "The Arrangement of the Camp (Part 4)",
    "The Arrangement of the Camp (Part 5)",
    "The Arrangement of the Camp (Part 6)",
    "The Arrangement of the Camp (Part 7)",
    "More Arrangements of the Camp",
    "Beginning of the March (Sinai to Kadesh Barnea)",
    "The March Continues",
    "The Murmuring of Miriam and Aaron against Moses",
    "At Kadesh—the 12 Spies",
    "The Unbelief of Israel at Kadesh",
    "The Wandering in the Wilderness (Part 1)",
    "The Wandering in the Wilderness (Part 2)",
    "The Wandering in the Wilderness (Part 3)",
    "The Wandering in the Wilderness (Part 4)",
    "The Wandering in the Wilderness (Part 5)",
    "No Water Situation #2",
    "The Serpent of Brass",
    "Balaam and Balak (Part 1)",
    "Balaam and Balak (Part 2)",
    "Balaam and Balak (Part 3)",
    "The Doctrine of Balaam",
    "New Generation Numbered",
    "Moses Prepares to Die, Joshua Appointed",
    "Instructions on Offerings (Part 1)",
    "Instructions on Offerings (Part 2)",
    "The Law of Vows",
    "The Judgment on Midian",
    "Reuben, Gad, ½ Tribe of Manasseh Choose Land East of Jordan",
    "40 Year Travelogue",
    "The Borders of Canaan",
    "The Cities of Refuge",
    "Inheritance Laws (Keep it in the Family)",
  ],
  // Deuteronomy (34 chapters)
  5: [
    "Moses' Sermon #1 (Part 1)",
    "Moses' Sermon #1 (Part 2)",
    "Moses' Sermon #1 (Part 3)",
    "Moses' Sermon #2 (Part 1)",
    "Moses' Sermon #2 (Part 2)",
    "Moses' Sermon #2 (Part 3)",
    "Moses' Sermon #2 (Part 4)",
    "Moses' Sermon #2 (Part 5)",
    "Moses' Sermon #2 (Part 6)",
    "Moses' Sermon #2 (Part 7)",
    "Moses' Sermon #2 (Part 8)",
    "Moses' Sermon #3 (Part 1)",
    "Moses' Sermon #3 (Part 2)",
    "Moses' Sermon #3 (Part 3)",
    "Moses' Sermon #3 (Part 4)",
    "Moses' Sermon #3 (Part 5)",
    "Moses' Sermon #3 (Part 6)",
    "Moses' Sermon #3 (Part 7)",
    "Moses' Sermon #3 (Part 8)",
    "Moses' Sermon #3 (Part 9)",
    "Moses' Sermon #3 (Part 10)",
    "Moses' Sermon #3 (Part 11)",
    "Moses' Sermon #3 (Part 12)",
    "Moses' Sermon #3 (Part 13)",
    "Moses' Sermon #3 (Part 14)",
    "Moses' Sermon #3 (Part 15)",
    "Moses' Sermon #3 (Part 16)",
    "Moses' Sermon #3 (Part 17)",
    "Moses' Sermon #3 (Part 18)",
    "Moses' Sermon #4 (Part 1)",
    "Moses' Sermon #4 (Part 2)",
    "Moses' Sermon #4 (Part 3)",
    "Moses' Song & Benediction",
    "Moses' Blessing on the Tribes",
    "Moses' Look at Canaan, Death, Burial",
  ],
  // Joshua (24 chapters)
  6: [
    "Joshua Assumes Leadership",
    "Rahab and the Spies",
    "Crossing the Jordan",
    "2 Memorials (Jordan River & Gilgal)",
    "The Unseen Captain",
    "The Conquest of Jericho",
    "Defeat at Ai",
    "Victory at Ai",
    "Deception of the Gibeonites",
    "Gibeon Campaign & Southern Campaign",
    "Final Conquest of Canaan",
    "The 31 Kings",
    "Division of the Land (Part 1)",
    "Division of the Land (Part 2)",
    "Division of the Land (Part 3)",
    "Division of the Land (Part 4)",
    "Division of the Land (Part 5)",
    "The Tabernacle at Shiloh",
    "Continued Division of the Land (Part 1)",
    "The Cities of Refuge",
    "Continued Division of the Land (Part 2)",
    "Rival, Schismatic Altar of Reuben & Gad",
    "Last Counsels of Joshua",
    "Joshua's Death",
  ],
  // Judges (21 chapters)
  7: [
    '"Neither Did" Chapter',
    "Institution of the Judges",
    "Gentlemen, Start Your Engines (Judges Begin to Rule)",
    "Deborah & Barak",
    "Song of Deborah & Barak",
    "Gideon and the Fleece",
    "Gideon's Victory, 300 Over Midian",
    "1st Jealousy of Ephraim; Death of Gideon",
    "False King Abimelech",
    "The Wickedness of Israel",
    "Jephthah the 9th Judge",
    "2nd Jealousy of Ephraim",
    "Samson's Parents",
    "Samson's Riddle",
    "Samson's Mighty Acts",
    "Samson and Delilah",
    "The Muddle of Micah",
    "Danite Invasion & Idolatry",
    "The Levite and His Concubine",
    "Tribe of Benjamin Nearly Destroyed",
    "How to Catch a Wife",
  ],
  // Ruth (4 chapters)
  8: [
    "Ruth & Naomi Return to Judah from Moab",
    "Ruth Harvests in Boaz's Fields",
    "Ruth and the Law of the Kinsman Redeemer",
    "Ruth Marries Boaz",
  ],
  // 1 Samuel (31 chapters)
  9: [
    "Hannah and the Birth of Samuel",
    "Samuel, Eli, Eli's Evil Sons",
    "The Call of Samuel",
    "Defeat, Ark Lost to Philistines",
    "Dagon vs. the Ark",
    "Ark Returned",
    "Ark at Home",
    "Israel Demands a King",
    "Saul Chosen",
    "Saul's Anointing",
    "Saul's Victory",
    "Samuel's Valedictory Address",
    "Saul's Rejection by God",
    "Jonathan's Victory over the Philistines",
    "Saul's Sheep Lie",
    "David Chosen and Anointed",
    "David & Goliath",
    "David & Jonathan",
    "David Flees from Saul",
    "Jonathan Protects David",
    "David Continues to Flee",
    "David's Mighty Men",
    "Their Adventures",
    "David Spares Saul #1",
    "Samuel Dies",
    "David Spares Saul #2",
    "David's Backsliding in Philistia",
    "Saul and the Witch of Endor",
    "David & Achish",
    "David and Ziklag (2 Wives Captured)",
    "The Death of Saul",
  ],
  // 2 Samuel (24 chapters)
  10: [
    "Saul & Jonathan's Death Told to David",
    "Civil War—Abner vs. David",
    "Civil War—House of Saul vs. David",
    "The Murder of Ish-Bosheth",
    "David Becomes King over Israel",
    "Ark to Jerusalem",
    "The Davidic Covenant Stated",
    "David the Mighty Conqueror",
    "David & Mephibosheth",
    "The Ammonite-Syrian War",
    "David's Sin with Bathsheba",
    "David's Confession of Sin",
    "Amnon's Crime (Immorality)",
    "Beautiful Absalom",
    "Absalom's Rebellion",
    "Absalom Enters Jerusalem",
    "Absalom Listens to False Counselors",
    "Absalom Hangs by His Hair & Dies",
    "David Gets With It",
    "Sheba's Revolt",
    "Three Years Famine",
    "David's Son of Deliverance",
    "David's Mighty Men",
    "David's Numbering Sin",
  ],
  // 1 Kings (22 chapters)
  11: [
    "David Failing, Solomon Anointed",
    "The Death of David",
    "Solomon's Prayer for Wisdom",
    "Solomon Gets Wisdom",
    "Solomon's Temple—The Building (Part 1)",
    "Solomon's Temple—The Building (Part 2)",
    "Solomon's Temple—The Building (Part 3)",
    "Solomon's Temple—The Dedication",
    "Solomon's Fame and Wealth",
    "Solomon & the Queen of Sheba",
    "The Backsliding and Death of Solomon (Rise of Jeroboam in the North)",
    "Split of the Kingdom (Rehoboam, Solomon's Son in the South)",
    "A Wicked Jeroboam",
    "Jeroboam and Rehoboam Die",
    "Abijam, Asa, Baasha, Nabad",
    "Some of Israel's Wicked Kings (Elah, Zimri, Tibni, Omri, Ahab)",
    "Elijah Fed by Ravens, Raising of the Widow's Son",
    "Elijah vs. Baal (Mt. Carmel)",
    "Elijah & Still, Small Voice",
    "Ahab and Victory over Syrians",
    "Ahab, Jezebel",
    "Micaiah—God's Man of Conviction",
  ],
  // 2 Kings (25 chapters)
  12: [
    "Elijah—Illness & Death of Ahaziah",
    "Elijah's Translation",
    "Elisha—Defeat of the Moabites",
    "Elisha's 5 Miracle Chapter",
    "The Healing of Naaman",
    "Elisha and the Lost Axe Head",
    'Elisha: "You Will Eat!"',
    "Elisha Predicts 7 Years of Famine",
    "Jehu the Furious Driver",
    "Judgment on Ahab's 70 Sons",
    "Only One Heir—Joash",
    "Repairing of the Temple",
    "Elisha Dies",
    "Civil War—Israel & Judah",
    "Various Kings of Israel",
    "Rule of Ahaz",
    "Assyrian Captivity and Why",
    "Reign of Hezekiah",
    "Isaiah and Hezekiah",
    "Hezekiah's 15 Year Extension & Death",
    "Evil King Manasseh",
    "Josiah—Rediscovery of the Law",
    "Word Read and Passover Kept",
    "Babylon Captivity—70 Years",
    "Babylon Captivity—Siege of Jerusalem",
  ],
  // 1 Chronicles (29 chapters)
  13: [
    "Genealogies (Part 1)",
    "Genealogies (Part 2)",
    "Genealogies (Part 3)",
    "Genealogies (Part 4)",
    "Genealogies (Part 5)",
    "Genealogies (Part 6)",
    "Genealogies (Part 7)",
    "Genealogies (Part 8)",
    "Genealogies (Part 9)",
    "Saul's Death",
    "David's Mighty Men (Part 1)",
    "David's Mighty Men (Part 2)",
    "Uzza and the Ark",
    "David and the Mulberry Trees",
    "Ark Returned",
    "David and a Psalm",
    "The Davidic Covenant",
    "David's Mighty Kingdom (then)",
    "The Ammonite-Syrian War",
    "The Giant with 24 Fingers and Toes",
    "David's Numbering Sin",
    "David Prepares Materials for the Temple",
    "Solomon Made King, Organization of Levitical Priests",
    "Organization of Israel Continued (Part 1)",
    "Organization of Israel Continued (Part 2)",
    "Organization of Israel Continued (Part 3)",
    "Organization of Israel Continued (Part 4)",
    "Closing Counsel of David, Teenage Solomon Reigns, David Dies",
  ],
  // 2 Chronicles (36 chapters)
  14: [
    "Solomon and His Wisdom",
    "Solomon Builds the Temple (Part 1)",
    "Solomon Builds the Temple (Part 2)",
    "Solomon Builds the Temple (Part 3)",
    "Ark Put in Temple, Glory Fills the Temple",
    "Solomon Dedicates the Temple",
    "The Lord is Pleased",
    "Solomon's Activity and Wealth",
    "Solomon and the Queen of Sheba",
    "Rehoboam Over 2 Southern Tribes (Part 1)",
    "Rehoboam Over 2 Southern Tribes (Part 2)",
    "Rehoboam Over 2 Southern Tribes (Part 3)",
    "Jeroboam Over 10 Northern Tribes",
    "Good King Asa (Part 1)",
    "Good King Asa (Part 2)",
    "Good King Asa (Part 3)",
    "Good King Jehoshaphat (Part 1)",
    "Good King Jehoshaphat (Part 2)",
    "Good King Jehoshaphat (Part 3)",
    "Good King Jehoshaphat (Part 4)",
    "Jehoram's Reign",
    "Only One Heir Left in the Royal Line of Christ, Joash",
    "Reign of Joash (Part 1)",
    "Reign of Joash (Part 2)",
    "Reign of Amaziah",
    "Reign of Uzziah",
    "Reign of Jothan",
    "Reign of Ahaz",
    "Reign of Hezekiah (Part 1)",
    "Reign of Hezekiah (Part 2)",
    "Reign of Hezekiah (Part 3)",
    "Reign of Hezekiah (Part 4)",
    "Reign of Manasseh",
    "Reign of Josiah (Part 1)",
    "Reign of Josiah (Part 2)",
    "The Babylonian Captivity",
  ],
  // Ezra (10 chapters)
  15: [
    "Decree of Cyrus (Restoration of the Temple)",
    "The Returning Remnant",
    "Temple Foundations Laid",
    "Opposition, Letter to Artaxerxes, Work Stopped",
    "Opposition Answered",
    "Decree of Darius (Temple Finished)",
    "Ezra Thanks the Lord",
    "Treasure Brought to the Temple",
    "Unholy (Mixed) Marriages, Ezra's Prayer",
    "The Above Sin is Judged and Restitution Made",
  ],
  // Nehemiah (13 chapters)
  16: [
    "The Ruined Walls",
    "Nehemiah Surveys the Ruins",
    "The Builders Begin to Build",
    "Opposition in the Rebuilding (Part 1)",
    "Opposition in the Rebuilding (Part 2)",
    "Opposition in the Rebuilding (Part 3)",
    "Genealogies",
    "Ezra's Expository Preaching",
    "Review of Old Testament History",
    "Application of Teaching to Experience",
    "Geographical Distribution of the Inhabitants of Israel",
    "Dedication of the Walls",
    "The Law and Separation",
  ],
  // Esther (10 chapters)
  17: [
    "Queen Vashti Disobeys the King",
    "Queen Esther the Jew",
    "Mordecai and Haman",
    "Planned Extermination of the Jewish Nation",
    '"If I Perish, I Perish"',
    "Haman Shamed",
    "Haman Hanged",
    "The Jews Delivered",
    "The Feast of Purim (Celebrating Jewish Deliverance)",
    "Mordecai, #2 in the Kingdom",
  ],
  // Job (42 chapters)
  18: [
    "Job and Suffering (Family)",
    "Job and Suffering (Personal - Part 1)",
    "Job and Suffering (Personal - Part 2)",
    "Eliphaz's First Prosecution",
    "Job's Defense (Part 1)",
    "Job's Defense (Part 2)",
    "Job's Defense (Part 3)",
    "Bildad's First Prosecution",
    "Job's Defense (Part 4)",
    "Job's Defense (Part 5)",
    "Zophar's First Prosecution",
    "Job's Defense (Part 6)",
    "Job's Defense (Part 7)",
    "Job's Defense (Part 8)",
    "Eliphaz's Second Prosecution",
    "Job's Defense (Part 9)",
    "Job's Defense (Part 10)",
    "Bildad's Second Prosecution",
    "Job's Defense (Part 11)",
    "Zophar's Final Arguments",
    "Job's Defense (Part 12)",
    "Eliphaz's Final Arguments",
    "Job's Reply to Eliphaz",
    "Bildad's Final Speech",
    "Job's Final Defense",
    "Zophar's Final Speech",
    "Job's Response",
    "Job's Final Monologue (Part 1)",
    "Job's Final Monologue (Part 2)",
    "Job's Final Monologue (Part 3)",
    "Elihu's First Speech",
    "Elihu's Second Speech",
    "Elihu's Third Speech",
    "Elihu's Fourth Speech",
    "The Lord's First Response",
    "The Lord's Second Response",
    "Job's Repentance and Humiliation",
    "The Lord Rebukes Job's Friends",
    "Job's Restoration",
    "Job's Final Days",
  ],
  // Psalms (150 chapters)
  19: Array.from({ length: 150 }, (_, i) => `Psalm ${i + 1}`),
  // Proverbs (31 chapters)
  20: Array.from({ length: 31 }, (_, i) => `Proverbs Chapter ${i + 1}`),
  // Ecclesiastes (12 chapters)
  21: [
    "Vanity of Vanities",
    "The Frustration of Life",
    "A Time for Everything",
    "The Futility of Toil",
    "Relationships and Solitude",
    "The Misery of Isolation",
    "The Value of Diligence",
    "Wealth Cannot Satisfy",
    "The Twilight Years",
    "Remember Your Creator",
    "Keeping Proper Balance",
    "The Final Word",
  ],
  // Song of Solomon (8 chapters)
  22: [
    "The First Day",
    "The Second Day (Evening)",
    "The Second Day (Night)",
    "The Third Day (Morning)",
    "The Third Day (Afternoon)",
    "The Third Day (Evening)",
    "The Third Day (Night)",
    "The Fourth Day (Morning)",
  ],
  // Isaiah (66 chapters)
  23: Array.from({ length: 66 }, (_, i) => `Isaiah Chapter ${i + 1}`),
  // Jeremiah (52 chapters)
  24: Array.from({ length: 52 }, (_, i) => `Jeremiah Chapter ${i + 1}`),
  // Lamentations (5 chapters)
  25: [
    "Jerusalem's Misery",
    "God's Wrath Against Israel",
    "God's Mercy Endures",
    "Prayer for Mercy",
    "Prayer for Restoration",
  ],
  // Ezekiel (48 chapters)
  26: Array.from({ length: 48 }, (_, i) => `Ezekiel Chapter ${i + 1}`),
  // Daniel (12 chapters)
  27: [
    "Daniel and His Friends",
    "Nebuchadnezzar's Dream",
    "The Golden Statue",
    "The Fiery Furnace",
    "The Handwriting on the Wall",
    "Daniel in the Lion's Den",
    "Daniel's First Vision",
    "Daniel's Vision of the Ram and Goat",
    "Daniel's Seventy Weeks",
    "Daniel's Vision of the Future",
    "The Time of the End (Part 1)",
    "The Time of the End (Part 2)",
  ],
  // Hosea (14 chapters)
  28: Array.from({ length: 14 }, (_, i) => `Hosea Chapter ${i + 1}`),
  // Joel (3 chapters)
  29: ["The Plague of Locusts", "The Day of the Lord", "The Outpouring of the Spirit"],
  // Amos (9 chapters)
  30: Array.from({ length: 9 }, (_, i) => `Amos Chapter ${i + 1}`),
  // Obadiah (1 chapter)
  31: ["The Judgment of Edom"],
  // Jonah (4 chapters)
  32: ["Jonah's Flight", "Jonah's Prayer", "Jonah's Preaching", "Jonah's Complaint"],
  // Micah (7 chapters)
  33: Array.from({ length: 7 }, (_, i) => `Micah Chapter ${i + 1}`),
  // Nahum (3 chapters)
  34: [
    "The Majesty of God",
    "The Fall of Nineveh (Part 1)",
    "The Fall of Nineveh (Part 2)",
  ],
  // Habakkuk (3 chapters)
  35: ["Habakkuk's Complaint", "The Lord's Response", "Habakkuk's Prayer"],
  // Zephaniah (3 chapters)
  36: ["The Day of the Lord's Wrath", "Call to Repentance", "The Joy of the Redeemed"],
  // Haggai (2 chapters)
  37: ["Rebuild the Temple", "The Glory of the New Temple"],
  // Zechariah (14 chapters)
  38: Array.from({ length: 14 }, (_, i) => `Zechariah Chapter ${i + 1}`),
  // Malachi (4 chapters)
  39: [
    "God's Love for Israel",
    "The Priests' Unfaithfulness",
    "The Messenger of the Covenant",
    "The Day of Judgment",
  ],
  // Matthew (28 chapters)
  40: Array.from({ length: 28 }, (_, i) => `Matthew Chapter ${i + 1}`),
  // Mark (16 chapters)
  41: Array.from({ length: 16 }, (_, i) => `Mark Chapter ${i + 1}`),
  // Luke (24 chapters)
  42: Array.from({ length: 24 }, (_, i) => `Luke Chapter ${i + 1}`),
  // John (21 chapters)
  43: Array.from({ length: 21 }, (_, i) => `John Chapter ${i + 1}`),
  // Acts (28 chapters)
  44: Array.from({ length: 28 }, (_, i) => `Acts Chapter ${i + 1}`),
  // Romans (16 chapters)
  45: Array.from({ length: 16 }, (_, i) => `Romans Chapter ${i + 1}`),
  // 1 Corinthians (16 chapters)
  46: Array.from({ length: 16 }, (_, i) => `1 Corinthians Chapter ${i + 1}`),
  // 2 Corinthians (13 chapters)
  47: Array.from({ length: 13 }, (_, i) => `2 Corinthians Chapter ${i + 1}`),
  // Galatians (6 chapters)
  48: Array.from({ length: 6 }, (_, i) => `Galatians Chapter ${i + 1}`),
  // Ephesians (6 chapters)
  49: Array.from({ length: 6 }, (_, i) => `Ephesians Chapter ${i + 1}`),
  // Philippians (4 chapters)
  50: Array.from({ length: 4 }, (_, i) => `Philippians Chapter ${i + 1}`),
  // Colossians (4 chapters)
  51: Array.from({ length: 4 }, (_, i) => `Colossians Chapter ${i + 1}`),
  // 1 Thessalonians (5 chapters)
  52: Array.from({ length: 5 }, (_, i) => `1 Thessalonians Chapter ${i + 1}`),
  // 2 Thessalonians (3 chapters)
  53: Array.from({ length: 3 }, (_, i) => `2 Thessalonians Chapter ${i + 1}`),
  // 1 Timothy (6 chapters)
  54: Array.from({ length: 6 }, (_, i) => `1 Timothy Chapter ${i + 1}`),
  // 2 Timothy (4 chapters)
  55: Array.from({ length: 4 }, (_, i) => `2 Timothy Chapter ${i + 1}`),
  // Titus (3 chapters)
  56: Array.from({ length: 3 }, (_, i) => `Titus Chapter ${i + 1}`),
  // Philemon (1 chapter)
  57: ["Paul's Letter to Philemon"],
  // Hebrews (13 chapters)
  58: Array.from({ length: 13 }, (_, i) => `Hebrews Chapter ${i + 1}`),
  // James (5 chapters)
  59: Array.from({ length: 5 }, (_, i) => `James Chapter ${i + 1}`),
  // 1 Peter (5 chapters)
  60: Array.from({ length: 5 }, (_, i) => `1 Peter Chapter ${i + 1}`),
  // 2 Peter (3 chapters)
  61: Array.from({ length: 3 }, (_, i) => `2 Peter Chapter ${i + 1}`),
  // 1 John (5 chapters)
  62: Array.from({ length: 5 }, (_, i) => `1 John Chapter ${i + 1}`),
  // 2 John (1 chapter)
  63: ["2 John"],
  // 3 John (1 chapter)
  64: ["3 John"],
  // Jude (1 chapter)
  65: ["Jude"],
  // Revelation (22 chapters)
  66: Array.from({ length: 22 }, (_, i) => `Revelation Chapter ${i + 1}`),
};

/**
 * Vietnamese chapter titles (tiêu đề chương). When present, used for sectionTitle (VI read view).
 * Books 1–5 filled; books 6–66 fall back to English in the seed.
 */
const BIBLE_CHAPTER_TITLES_VI: Partial<Record<number, string[]>> = {
  // Genesis (50 chapters)
  1: [
    "Sự Sáng Tạo",
    "Ngày Thứ Bảy",
    "Sự Sa Ngã",
    "Ca-in và A-bên",
    "Dòng Dõi Từ A-đam Đến Nô-ê",
    "Sự Tham Nhũng Của Nhân Loại",
    "Đại Hồng Thủy",
    "Nước Rút",
    "Giao Ước Với Nô-ê",
    "Các Dân Tộc Từ Con Cái Nô-ê",
    "Tòa Tháp Ba-bel",
    "Chúa Gọi Áp-ram",
    "Áp-ram Và Lót Chia Tách",
    "Áp-ram Cứu Lót",
    "Giao Ước Của Chúa Với Áp-ram",
    "Ha-gar Và Ích-ma-ên",
    "Dấu Của Giao Ước",
    "Ba Vị Khách Thăm Viếng",
    "Sô-đôm Và Gô-mô-ra Bị Phá Huỷ",
    "Áp-ra-ham Và A-bi-mê-léc",
    "I-sác Được Sinh Ra",
    "Đức Tin Của Áp-ra-ham Được Thử Thách",
    "Cái Chết Của Xa-ra",
    "Vợ Cho I-sác",
    "Cái Chết Của Áp-ra-ham",
    "I-sác Và A-bi-mê-léc",
    "Gia-cốp Được Phước Lành Của I-sác",
    "Chiêm Bao Của Gia-cốp",
    "Gia-cốp Gặp Ra-chên",
    "Con Cái Của Gia-cốp",
    "Gia-cốp Bỏ Chạy Khỏi La-ban",
    "Gia-cốp Chuẩn Bị Gặp Ê-sau",
    "Gia-cốp Và Ê-sau Hòa Hợp",
    "Đi-na Và Người Sê-chem",
    "Gia-cốp Trở Lại Bê-tên",
    "Dòng Dõi Của Ê-sau",
    "Chiêm Bao Của Giô-sép",
    "Giu-đa Và Ta-má",
    "Giô-sép Trong Nhà Phô-ti-pha",
    "Giô-sép Giải Mộng",
    "Chiêm Bao Của Pha-ra-ô",
    "Các Anh Của Giô-sép Đến Ê-díp-tô",
    "Chuyến Đi Thứ Hai Đến Ê-díp-tô",
    "Giô-sép Thử Các Anh",
    "Giô-sép Bộc Lộ Danh Tính",
    "Gia-cốp Đi Đến Ê-díp-tô",
    "Giô-sép Cho Gia Đình Định Cư Ở Ê-díp-tô",
    "Gia-cốp Chúc Phước Con Trai Của Giô-sép",
    "Gia-cốp Chúc Phước Con Trai",
    "Cái Chết Của Gia-cốp Và Giô-sép",
  ],
  // Exodus (40 chapters)
  2: [
    "Người Y-sơ-ra-ên Bị Áp Bức",
    "Sự Sinh Ra Của Môi-se",
    "Bụi Cây Cháy",
    "Những Dấu Hiệu Cho Môi-se",
    "Môi-se Đối Đầu Với Pha-ra-ô",
    "Chúa Tân Hứa Sự Giải Phóng",
    "Giao Ước Của Chúa Với Môi-se",
    "Những Tai Họa: Ếch Và Muỗi",
    "Những Tai Họa: Ruồi Và Gia Súc",
    "Những Tai Họa: Bóng Tối Và Châu Chấu",
    "Tai Họa Các Con Đầu Lòng",
    "Lễ Vượt Qua Và Cuộc Thoát Ly",
    "Dành Riêng Con Đầu Lòng",
    "Qua Biển Đỏ",
    "Bài Hát Của Môi-se",
    "Bánh Manna Và Cút Chơi",
    "Nước Từ Tảng Đá",
    "Giê-tơ-rô Thăm Môi-se",
    "Ở Núi Si-nai",
    "Mười Điều Răn",
    "Luật Về Những Người Tôi Tớ Hê-bơ-rơ",
    "Luật Về Tài Sản",
    "Luật Về Công Lý Và Lòng Thương Xót",
    "Giao Ước Được Xác Nhận",
    "Hòm Giao Ước",
    "Đền Tạm",
    "Bàn Thờ Đồng",
    "Áo Của Thầy Tế Lễ",
    "Phong Chức Thầy Tế Lễ",
    "Bàn Thờ Hương Liệu",
    "Bê-xan-ên Và Các Thợ Thủ Công",
    "Bê Vàng",
    "Sự Hiện Diện Của Chúa Với Môi-se",
    "Những Bảng Đá Mới",
    "Ngày Sa-bát Và Sự Đóng Góp Cho Đền Tạm",
    "Xây Dựng Đền Tạm",
    "Làm Hòm Giao Ước Và Những Vật Khác",
    "Làm Bàn Thờ Đồng Và Chậu",
    "Làm Áo Của Thầy Tế Lễ",
    "Dựng Đền Tạm",
  ],
  // Leviticus (27 chapters)
  3: [
    "Lễ Toàn Thiêu",
    "Lễ Dâng Lúa Mì",
    "Lễ Hiệp Hòa",
    "Lễ Tế Lễ Để Chuộc Tội",
    "Lễ Tế Lễ Để Bồi Thường",
    "Những Quy Định Thêm Về Lễ Tế",
    "Thêm Những Quy Định Về Lễ Tế",
    "Phong Chức Cho A-rôn Và Con Trai",
    "Thầy Tế Lễ Bắt Đầu Thờ Phụng",
    "Cái Chết Của Na-đáp Và A-bi-hu",
    "Động Vật Sạch Và Bẩn",
    "Tinh Tẩy Sau Khi Sinh Con",
    "Những Bệnh Về Da Có Thể Lây Lan",
    "Tinh Tẩy Khỏi Những Bệnh Lây Lan",
    "Những Tiết Dịch Gây Bẩn",
    "Ngày Chuộc Tội",
    "Cấm Ăn Máu",
    "Những Mối Quan Hệ Tình Dục Bất Hợp Pháp",
    "Những Luật Lệ Khác Nhau",
    "Những Hình Phạt Cho Tội Lỗi",
    "Những Quy Tắc Cho Thầy Tế Lễ",
    "Những Lễ Tế Không Được Chấp Nhận",
    "Những Lễ Hội Được Chỉ Định",
    "Dầu Ôliu, Bánh Mì, Và Lạm Dụng Tên Chúa",
    "Năm Sa-bát Và Năm Hoan Hỷ",
    "Phước Lành Cho Sự Vâng Lời",
    "Những Lời Thề Và Những Vật Dâng Riêng",
  ],
  // Numbers (36 chapters)
  4: [
    "Cuộc Điểm Danh Người Y-sơ-ra-ên",
    "Sự Sắp Xếp Của Các Trại",
    "Những Người Lê-vi",
    "Những Chi Tộc Của Người Lê-vi",
    "Tinh Khiết Của Trại",
    "Lời Thề Na-xa-raê",
    "Những Lễ Tế Tại Lễ Khánh Thành Đền Tạm",
    "Dựng Đèn Và Phong Chức Cho Người Lê-vi",
    "Lễ Vượt Qua",
    "Những Cái Kèn Bạc Và Sự Ra Đi Khỏi Si-nai",
    "Lửa Từ Chúa Và Cút Chơi",
    "Mi-ri-am Và A-rôn Phản Đối Môi-se",
    "Thăm Dò Đất Ca-na-an",
    "Dân Y-sơ-ra-ên Từ Chối Lời Hứa",
    "Những Lễ Tế Khác Nhau Và Luật Lệ",
    "Sự Nổi Loạn Của Cô-rah",
    "Cây Gậy Của A-rôn Nảy Lộc",
    "Nhiệm Vụ Của Thầy Tế Lễ Và Người Lê-vi",
    "Nước Để Tinh Tẩy",
    "Nước Từ Tảng Đá",
    "Người Y-sơ-ra-ên Đánh Bại Xi-hôn Và Ôg",
    "Ba-lác Gọi Ba-la-am",
    "Những Lời Tiên Tri Của Ba-la-am",
    "Những Lời Tiên Tri Cuối Cùng Của Ba-la-am",
    "Sự Gây Dâm Ô Của Người Y-sơ-ra-ên Tại Phê-ô",
    "Cuộc Điểm Danh Thứ Hai",
    "Con Gái Của Xê-lô-phê-hát",
    "Những Lễ Tế Hàng Ngày Và Định Kỳ",
    "Những Lễ Tế Cho Những Lễ Hội",
    "Những Lời Thề",
    "Trả Thù Người Mi-đi-an",
    "Các Chi Tộc Ở Phía Bên Kia Sông Giô-đan",
    "Những Chặng Đường Của Người Y-sơ-ra-ên",
    "Biên Giới Của Đất",
    "Những Thành Phố Cho Người Lê-vi",
    "Di Sản Của Con Gái Xê-lô-phê-hát",
  ],
  // Deuteronomy (34 chapters)
  5: [
    "Hành Trình Đến Hô-rếp",
    "Lạc Đường Trong Hoang Dã",
    "Đánh Bại Ôg Và Xi-hôn",
    "Khuyến Khích Tuân Theo",
    "Mười Điều Răn",
    "Điều Răn Vĩ Đại",
    "Đuổi Các Quốc Gia Ra",
    "Đừng Quên Chúa Trời Của Bạn",
    "Không Phải Vì Công Lý Của Y-sơ-ra-ên",
    "Bê Vàng Và Lòng Thương Xót Của Chúa",
    "Yêu Thương Và Tuân Theo Chúa",
    "Nơi Duy Nhất Để Thờ Phụng",
    "Thờ Phụng Các Vị Thần Khác",
    "Thực Phẩm Sạch Và Bẩn",
    "Năm Để Hủy Bỏ Nợ",
    "Lễ Vượt Qua Và Những Lễ Hội",
    "Tòa Án, Vua, Và Các Tiên Tri",
    "Những Lễ Tế Cho Thầy Tế Lễ Và Người Lê-vi",
    "Những Thành Phố Trốn Tránh",
    "Đi Chiến Tranh",
    "Những Luật Lệ Khác Nhau",
    "Luật Lệ Và Cấm Chỉ",
    "Loại Trừ Khỏi Đại Hội",
    "Những Luật Lệ Linh Tinh",
    "Luật Bảo Vệ Và Di Sản",
    "Những Trái Đầu Mùa Và Của Lễ Một Phần Mười",
    "Bàn Thờ Trên Núi Ê-ban",
    "Phước Lành Và Lời Nguyền Rủa",
    "Tân Hành Giao Ước",
    "Thịnh Vượng Sau Khi Quay Về Với Chúa",
    "Giô-suê Thay Thế Môi-se",
    "Bài Hát Của Môi-se",
    "Môi-se Chúc Phước Cho Các Chi Tộc",
    "Cái Chết Của Môi-se",
  ],
};

export async function seedBibleChapterSubtitles() {
  try {
    console.log("🌱 Seeding Bible chapter subtitles into BibleChapter.sectionTitle* ...");

    // Get all books in canonical order
    const books = await prisma.bibleBook.findMany({
      orderBy: { order: "asc" },
      select: { id: true, order: true, nameEn: true, chapterCount: true },
    });

    let updated = 0;

    for (const book of books) {
      const titlesEN = BIBLE_CHAPTER_TITLES_EN[book.order];
      if (!titlesEN) {
        console.warn(`⚠️  No titles found for book order ${book.order} (${book.nameEn})`);
        continue;
      }
      if (titlesEN.length < book.chapterCount) {
        console.warn(
          `⚠️  Book order ${book.order} (${book.nameEn}): only ${titlesEN.length} titles for ${book.chapterCount} chapters; skipping.`
        );
        continue;
      }
      const titlesVI = BIBLE_CHAPTER_TITLES_VI[book.order];

      for (let chapterNum = 1; chapterNum <= book.chapterCount; chapterNum++) {
        const i = chapterNum - 1;
        const en = titlesEN[i];
        if (!en) continue;
        const vi = titlesVI && titlesVI[i];
        await prisma.bibleChapter.update({
          where: { bookId_chapterNumber: { bookId: book.id, chapterNumber: chapterNum } },
          data: {
            sectionTitle: vi ?? en,
            sectionTitleKJV: en,
            sectionTitleNIV: en,
          },
        });
        updated++;
      }
    }

    console.log(`✅ Updated section titles for ${updated} chapter(s).`);
  } catch (error) {
    console.error("❌ Error seeding chapter subtitles:", error);
    throw error;
  } finally {
    await prisma.$disconnect();
  }
}

// Run the seed when invoked directly
seedBibleChapterSubtitles()
  .then(() => process.exit(0))
  .catch(() => process.exit(1));

